baseURL = "https://mitelman.engineering/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Alex Mitelman"
theme = "fuji2"

enableEmoji = true
enableRobotsTXT = true
[outputs]
  home = ["HTML", "RSS"]

[params]
  author = "Alex Mitelman" # You can also set author in post front matter individually
  subTitle = "Personal website"
  showWordCounter = true
  showReadTime = true

  # Posts shown in homepage
  mainSections = ["blog", "system-design-weekly"]

googleAnalytics = "UA-180800968-1"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "System Design Weekly"
    url = "/system-design-weekly/"
    weight = 2
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4

  [[menu.link]]
    name = "Email"
    url = "mailto:alex@mitelman.engineering"
    weight = 1
  [[menu.link]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alex-mitelman/"
    weight = 2
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/alex_mitelman"
    weight = 3