baseURL = "https://mitelman.engineering/"
languageCode = "en-us"
title = "Alex Mitelman: personal website"
theme = "fuji2"

googleAnalytics = "UA-180800968-1"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
